; Exact root filenames from the retired SDK 2.4.0 component packages:
; AI 2.4.4, ML / MachineLearning 2.1.74, Widgets 2.0.5, Search 2.4.4.
; Never remove a name supplied by the new payload. No directory/wildcard cleanup.
!macro RetireUnusedSdkFile NAME
  !if /FileExists "${PAYLOAD_DIR}\${NAME}"
    ; This runtime file is still required by the current package.
  !else
    Delete /REBOOTOK "$INSTDIR\${NAME}"
  !endif
!macroend

!macro RetireUnusedSdkComponents
  !insertmacro RetireUnusedSdkFile "DirectML.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Graphics.Imaging.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Graphics.Imaging.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Graphics.ImagingInternal.ImageObjectRemover.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Graphics.ImagingInternal.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Graphics.Internal.Imaging.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.AICapabilities.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.ContentModerationInternal.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.ContentSafety.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.ContentSafety.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.Foundation.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.FoundationInternal.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.GenerativeInternal.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.Imaging.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.Imaging.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.MachineLearning.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.MachineLearning.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.Text.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.Text.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.Video.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.Video.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.AI.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.ImageCreationInternal.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Internal.AI.ContentModeration.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Internal.AI.Generative.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Internal.ImageCreation.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Internal.SemanticSearch.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Internal.Vision.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Private.Workloads.SessionManager.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.PrivateCommon.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Search.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Search.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.SemanticSearch.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.SemanticSearchInternal.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Vision.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.VisionInternal.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Widgets.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Widgets.winmd"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Workloads.Resources.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Workloads.Resources_ec.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Workloads.dll"
  !insertmacro RetireUnusedSdkFile "Microsoft.Windows.Workloads.winmd"
  !insertmacro RetireUnusedSdkFile "NPUDetect.dll"
  !insertmacro RetireUnusedSdkFile "PerceptiveStreaming.dll"
  !insertmacro RetireUnusedSdkFile "SessionHandleIPCProxyStub.dll"
  !insertmacro RetireUnusedSdkFile "onnxruntime.dll"
  !insertmacro RetireUnusedSdkFile "workloads.365.json"
  !insertmacro RetireUnusedSdkFile "workloads.j32.json"
  !insertmacro RetireUnusedSdkFile "workloads.json"
  !insertmacro RetireUnusedSdkFile "workloads.lnl.json"
  !insertmacro RetireUnusedSdkFile "workloads.qnn.json"
  !insertmacro RetireUnusedSdkFile "workloads.stx.json"
!macroend
